import XCTest

/// Sanity checks over the committed raw `MATH` table fixtures in
/// `Tests/fixtures/math-table/` (regenerated by `MathTableFixtureExtraction`
/// in VinculumRenderTests on a Mac; consumed here on any platform).
///
/// These bytes are the ground truth the MATH-table parser is developed
/// against, headless and Linux-runnable. This test proves the fixture path
/// works end-to-end; the parser's own tests (Phase 1 of
/// docs/IMPLEMENTATION_PLAN.md) assert real values against these bytes.
final class MathTableFixtureTests: XCTestCase {

    private var fixtureDirectory: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
            .appendingPathComponent("Tests/fixtures/math-table")
    }

    private func bigEndianU16(_ bytes: [UInt8], _ offset: Int) -> Int? {
        guard offset >= 0, offset + 1 < bytes.count else { return nil }
        return Int(bytes[offset]) << 8 | Int(bytes[offset + 1])
    }

    func testFixturesExistAndCarryTheExpectedHeader() throws {
        let files = try FileManager.default
            .contentsOfDirectory(at: fixtureDirectory, includingPropertiesForKeys: nil)
            .filter { $0.pathExtension == "bin" }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
        XCTAssertFalse(files.isEmpty, "no MATH table fixtures committed")

        for file in files {
            let bytes = [UInt8](try Data(contentsOf: file))
            let name = file.lastPathComponent

            // MATH header: majorVersion(2)=1 · minorVersion(2)=0 ·
            // mathConstants@4 · mathGlyphInfo@6 · mathVariants@8.
            XCTAssertEqual(bigEndianU16(bytes, 0), 1, "\(name): major version")
            XCTAssertEqual(bigEndianU16(bytes, 2), 0, "\(name): minor version")

            // All three sub-tables must be present and in-bounds: Phase 1
            // parses mathConstants and mathGlyphInfo; mathVariants is what
            // the 0.23 delimiter provider already reads.
            for (label, offset) in [("mathConstants", 4), ("mathGlyphInfo", 6), ("mathVariants", 8)] {
                let sub = try XCTUnwrap(bigEndianU16(bytes, offset), "\(name): truncated header")
                XCTAssertGreaterThan(sub, 0, "\(name): \(label) sub-table missing")
                XCTAssertLessThan(sub, bytes.count, "\(name): \(label) offset out of bounds")
            }
        }
    }
}
